// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('c:/Users/Usuario/Desktop/Faculdade/LabProg/ActionsRPG/node_modules/react');
var { Component } = React;
var ReactNative = require('c:/Users/Usuario/Desktop/Faculdade/LabProg/ActionsRPG/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('ActionsRPG', appParameters);
});
require('c:/Users/Usuario/Desktop/Faculdade/LabProg/ActionsRPG/index.android.js');